/*
			Copyright <SWGEmu>
	See file COPYING for copying conditions.*/

package server.zone.objects.creature.buffs;

import server.zone.objects.creature.CreatureObject;
import server.zone.objects.creature.buffs.Buff;
import server.zone.objects.creature.buffs.FsResurrectBuffObserver;
import server.zone.objects.tangible.misc.FsBuffItem;
include server.zone.managers.object.ObjectManager;
include templates.params.ObserverEventType;
include server.zone.objects.creature.buffs.BuffType;

@json
class FsResurrectBuff extends Buff {
	protected FsResurrectBuffObserver observer;
	protected CreatureObject player;
	protected FsBuffItem sourceItem;

	public FsResurrectBuff(CreatureObject creo, unsigned int buffCRC, float duration, FsBuffItem item) {
		super(creo, buffCRC, duration, BuffType.OTHER);

		player = creo;
		sourceItem = item;
	}

	@dirty
	public CreatureObject getPlayer() {
		return player;
	}

	@dirty
	public FsBuffItem getSourceItem() {
		return sourceItem;
	}

	@preLocked
	public native void activate();

	@preLocked
	public native void deactivate();

	@preLocked
	private native void addObservers();

	@preLocked
	private native void dropObservers();
}
